---
title: "Whale That's Cool"
output:
  pdf_document: default
  html_document: default
---


```{r packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(broom)
library(janitor)
library(readxl)
library(xlsx)
library(raster)
library(rJava)

#add rgdal later
```


longitude: [-90.00, 30.00]
latitude: [-180, 0.00]

```{r south-atlantic}
library(readxl)
southatl <- read_excel("southatlantic.xlsx")

southatl <- southatl %>%
    mutate(Lon = as.numeric(Lon,  options(digits=5)), #make five digits)
         Lat = as.numeric(Lat,  options(digits=5))) 

```

```{r}
southatl %>%
  count(Species)
```

There are more Sperm than Right Whales in this region, but they are comparable.

```{r right-whales-sa}
sp_sa <- southatl %>%
  filter(Species == "Sperm")

absense_sa <- southatl %>% 
  filter(Encounter == "NoEnc")
```


```{r map-sa}
library(maptools)
## Checking rgeos availability: TRUE
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-90, 30), ylim=c(-60, 0), axes=TRUE, 
     col="light yellow", xlab = "Longitude", ylab = "Latitude")

#zoom in on south atlantic

# restore the box around the map
box()

# add the points
points(absense_sa$Lon, absense_sa$Lat, col='black', pch=16, cex=0.0001)
# plot points again to add a border, for better visibility
points(absense_sa$Lon, absense_sa$Lat, col='dark blue', cex=0.0001,)

# add the points
points(sp_sa$Lon, sp_sa$Lat, col='green', pch=20, cex=0.0001)
# plot points again to add a border, for better visibility
points(sp_sa$Lon, sp_sa$Lat, col='pale green', cex=0.0001)

# add the points
points(rw_sa$Lon, rw_sa$Lat, col='orange', pch=20, cex=0.0001)
# plot points again to add a border, for better visibility
points(rw_sa$Lon, rw_sa$Lat, col='red', cex=0.0001)

#red is right
#green is sperm
#blue is absense

```

```{r map-right-whale-sa}
library(maptools)
## Checking rgeos availability: TRUE
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-90, 30), ylim=c(-60, 0), axes=TRUE, 
     col="light yellow", xlab = "Longitude", ylab = "Latitude")

#zoomed in on South Atlantic
# restore the box around the map
box()

# add the points
points(absense_sa$Lon, absense_sa$Lat, col='black', pch=16, cex=0.0001)
# plot points again to add a border, for better visibility
points(absense_sa$Lon, absense_sa$Lat, col='dark blue', cex=0.0001,)

# add the points
points(rw_sa$Lon, rw_sa$Lat, col='orange', pch=20, cex=0.0001)
# plot points again to add a border, for better visibility
points(rw_sa$Lon, rw_sa$Lat, col='red', cex=0.0001)

#red is right
#blue is absense

```


```{r map-sperm-whales-sa}
library(maptools)
## Checking rgeos availability: TRUE
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-90, 30), ylim=c(-60, 0), axes=TRUE, 
     col="light yellow", xlab = "Longitude", ylab = "Latitude")

#zoom in on south atlantic

# restore the box around the map
box()

# add the points
points(absense_sa$Lon, absense_sa$Lat, col='black', pch=16, cex=0.0001)
# plot points again to add a border, for better visibility
points(absense_sa$Lon, absense_sa$Lat, col='dark blue', cex=0.0001,)

# add the points
points(sp_sa$Lon, sp_sa$Lat, col='green', pch=20, cex=0.0001)
# plot points again to add a border, for better visibility
points(sp_sa$Lon, sp_sa$Lat, col='pale green', cex=0.0001)


#green is sperm
#blue is absense
```

```{r count-month}
sp_sa_szn <- sp_sa %>% 
  mutate(Season = case_when(Month < 3.1 ~ "Summer",
                           Month > 3.1 & Month < 6.1 ~ "Fall", 
                           Month > 6.1 & Month < 9.1 ~ "Winter",
                           Month > 9.1 ~ "Spring")) 

sp_sa_szn %>%
  count(Season)

```


```{r making_season_datasets}
spring <- sp_sa_szn %>%
  filter(Season == "Spring")

summer <- sp_sa_szn %>%
  filter(Season == "Summer")

fall <- sp_sa_szn %>%
  filter(Season == "Fall")

winter <- sp_sa_szn %>%
  filter(Season == "Winter")
```


```{r mapping-seasons}
library(maptools)
## Checking rgeos availability: TRUE
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-90, 30), ylim=c(-60, 0), axes=TRUE, 
     col="light yellow", xlab = "Longitude", ylab = "Latitude")

#zoom in on south atlantic

# restore the box around the map
box()

points(absense_sa$Lon, absense_sa$Lat, col='black', pch=16, cex=0.0001)
# plot points again to add a border, for better visibility
points(absense_sa$Lon, absense_sa$Lat, col='black', cex=0.0001,)

# add the points
points(winter$Lon, winter$Lat, col='blue', pch=16, cex=0.0001)
# plot points again to add a border, for better visibility
points(winter$Lon, winter$Lat, col='blue', cex=0.0001,)

# add the points
points(spring$Lon, spring$Lat, col='green', pch=20, cex=0.0001)
# plot points again to add a border, for better visibility
points(spring$Lon, spring$Lat, col='green', cex=0.0001)

# add the points
points(summer$Lon, summer$Lat, col='red', pch=20, cex=0.0001)
# plot points again to add a border, for better visibility
points(summer$Lon, summer$Lat, col='red', cex=0.0001)

# add the points
points(fall$Lon, fall$Lat, col='purple', pch=20, cex=0.0001)
# plot points again to add a border, for better visibility
points(fall$Lon, fall$Lat, col='purple', cex=0.0001)



```


```{r world}
library(maptools)
## Checking rgeos availability: TRUE
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-90, 30), ylim=c(-60, 0), axes=TRUE, 
     col="light yellow", xlab = "Longitude", ylab = "Latitude")
# add the points
points(summer$Lon, summer$Lat, col='red', pch=20, cex=0.0001)
# plot points again to add a border, for better visibility
points(summer$Lon, summer$Lat, col='red', cex=0.0001)

```

```{r world-spr}
library(maptools)
## Checking rgeos availability: TRUE
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-90, 30), ylim=c(-60, 0), axes=TRUE, 
     col="light yellow", xlab = "Longitude", ylab = "Latitude")
# add the points
points(spring$Lon, spring$Lat, col='green', pch=20, cex=0.0001)
# plot points again to add a border, for better visibility
points(spring$Lon, spring$Lat, col='green', cex=0.0001)

```
```{r mapping-winter}
library(maptools)
## Checking rgeos availability: TRUE
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-90, 30), ylim=c(-60, 0), axes=TRUE, 
     col="light yellow", xlab = "Longitude", ylab = "Latitude")

#zoom in on south atlantic

# restore the box around the map
box()

# add the points
points(winter$Lon, winter$Lat, col='blue', pch=16, cex=0.0001)
# plot points again to add a border, for better visibility
points(winter$Lon, winter$Lat, col='blue', cex=0.0001,)

```

```{r world-fall}
library(maptools)
## Checking rgeos availability: TRUE
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-90, 30), ylim=c(-60, 0), axes=TRUE, 
     col="light yellow", xlab = "Longitude", ylab = "Latitude")
# add the points
points(fall$Lon, fall$Lat, col='red', pch=20, cex=0.0001)
# plot points again to add a border, for better visibility
points(fall$Lon, fall$Lat, col='red', cex=0.0001)

```

```{r year-histogram}
ggplot(data = sp_sa, mapping = aes(x = Year)) +
  geom_histogram()
```
1820 - 1860 has the most data
