---
title: "Whale That's Cool"
output:
  pdf_document: default
  html_document: default
---

```{r packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(broom)
library(janitor)
library(readxl)
library(xlsx)
library(raster)
library(rJava)

#add rgdal later
```



```{r loading-valpraiso}
valpraiso <- read_xlsx("valpraiso.xlsx")

# need install.packages("janitor")
# changes first row to column names
valpraiso <- janitor::row_to_names(valpraiso, 1) 
```

```{r exploring-count}
valpraiso %>% count(Species)

#appears that right whales are the most seen in the south

right_whales <- valpraiso %>%
  filter(Species == "Right")
```

```{r converting-to-numeric}
valpraiso <- valpraiso %>% 
  mutate(Lon = as.numeric(Lon,  options(digits=5)), #make five digits)
         Lat = as.numeric(Lat,  options(digits=5))) 
```


```{r latitude-longitude}
ggplot(valpraiso, aes(x = Lon, y = Lat, color = Species)) +
  geom_point()

#this doesn't make sense to use
```

```{r map?}
library(maptools)
## Checking rgeos availability: TRUE
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-180,180), ylim=c(-70,-30), axes=TRUE, 
     col="light yellow")
# restore the box around the map
box()
# add the points
points(valpraiso$Lon, valpraiso$Lat, col='orange', pch=20, cex=0.001)
# plot points again to add a border, for better visibility
points(valpraiso$Lon, valpraiso$Lat, col='red', cex=0.001)
```


```{r map-right-whale?}
library(maptools)
## Checking rgeos availability: TRUE
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-85, 35), ylim=c(-65,-25), axes=TRUE, 
     col="light yellow", xlab = "Longitude", ylab = "Latitude")

#zoomed in a bit on Argentina and right whales

# restore the box around the map
box()
# add the points
points(right_whales$Lon, right_whales$Lat, col='orange', pch=20, cex=0.2)
# plot points again to add a border, for better visibility
points(right_whales$Lon, right_whales$Lat, col='red', cex=0.2)
```


ok what if i want the entire south atlantic? not just south of valpraiso
longitude: [-90.00, 30.00]
latitude: [-180, 0.00]

```{r south-atlantic}
library(readxl)
southatl <- read_excel("southatlantic.xlsx")

southatl <- southatl %>%
    mutate(Lon = as.numeric(Lon,  options(digits=5)), #make five digits)
         Lat = as.numeric(Lat,  options(digits=5))) 

```

```{r}
southatl %>%
  count(Species)
```

There are more Sperm than Right Whales in this region, but they are comparable.

```{r right-whales-sa}
rw_sa <- southatl %>%
  filter(Species == "Right")

sp_sa <- southatl %>%
  filter(Species == "Sperm")

absense_sa <- southatl %>% 
  filter(Encounter == "NoEnc")
```


```{r map-right-whale-sa}
library(maptools)
## Checking rgeos availability: TRUE
data(wrld_simpl)
plot(wrld_simpl, xlim=c(-90, 30), ylim=c(-60, 0), axes=TRUE, 
     col="light yellow", xlab = "Longitude", ylab = "Latitude")

#zoomed in a bit on Argentina and right whales

# restore the box around the map
box()

# add the points
points(absense_sa$Lon, absense_sa$Lat, col='black', pch=16, cex=0.0001)
# plot points again to add a border, for better visibility
points(absense_sa$Lon, absense_sa$Lat, col='dark blue', cex=0.0001,)

# add the points
points(sp_sa$Lon, sp_sa$Lat, col='green', pch=20, cex=0.0001)
# plot points again to add a border, for better visibility
points(sp_sa$Lon, sp_sa$Lat, col='pale green', cex=0.0001)

# add the points
points(rw_sa$Lon, rw_sa$Lat, col='orange', pch=20, cex=0.0001)
# plot points again to add a border, for better visibility
points(rw_sa$Lon, rw_sa$Lat, col='red', cex=0.0001)

#red is right
#green is sperm
#gray is absense

```



